

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: moex_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Приложение MOEX Data Fetcher
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/moex_data
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: False
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        echo 'Creating tables...' &&
        python create_tables.py &&
        echo 'Starting application...' &&
        uvicorn engine.app:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
